Apply a patch that is necessary for some versions of Git
$ git log -1 ebae9ff95de2d0b36b061c7db833df4f7e01a41d
commit ebae9ff95de2d0b36b061c7db833df4f7e01a41d
Author: Jonathan Nieder <jrnieder@gmail.com>
Date:   Fri Mar 18 15:23:52 2011 -0500

    compat: add missing #include <sys/resource.h>

    Starting with commit c793430 (Limit file descriptors used by packs,
    2011-02-28), git uses getrlimit to tell how many file descriptors it
    can use.  Unfortunately it does not include the header declaring that
    function, resulting in compilation errors:

     sha1_file.c: In function 'open_packed_git_1':
     sha1_file.c:718: error: storage size of 'lim' isn't known
     sha1_file.c:721: warning: implicit declaration of function 'getrlimit'
     sha1_file.c:721: error: 'RLIMIT_NOFILE' undeclared (first use in this function)
     sha1_file.c:718: warning: unused variable 'lim'

    The standard header to include for this is <sys/resource.h> (which on
    some systems itself requires declarations from <sys/types.h> or
    <sys/time.h>).  Probably the problem was missed until now because in
    current glibc sys/resource.h happens to be included by sys/wait.h.

    MinGW does not provide sys/resource.h (and compat/mingw takes care of
    providing getrlimit some other way), so add the missing #include to
    the "#ifndef __MINGW32__" block in git-compat-util.h.

    Reported-by: Stefan Sperling <stsp@stsp.name>
    Tested-by: Stefan Sperling <stsp@stsp.name> [on OpenBSD]
    Tested-by: Arnaud Lacombe <lacombar@gmail.com> [on FreeBSD 8]
    Signed-off-by: Jonathan Nieder <jrnieder@gmail.com>
    Signed-off-by: Junio C Hamano <gitster@pobox.com>